FlightWeb/Models/Flight.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FlightWeb.Models
{
    public class Flight
    {
        [Key] 
        public int FlightId { get; set; }
        [Required,MaxLength(70)]
        [Display(Name ="Flight Name")]
        public string FlightName { get; set; }

        [Required, MaxLength(70)]
        [Display(Name = "Departure Airport")]
        public string Departure { get; set; }
        [Required, MaxLength(70)]
        [Display(Name = "Destination Airport")]
        public string Destination { get; set; }

        [Display(Name = "Departure Airport")]
        public string DepartureCode { get; set; }
        [Display(Name = "Destination Airport")]
        public string DestinationCode { get; set; }

        [Display(Name = "Flight distance (m)")]
        public string FlightDistance { get; set; }

        [Display(Name = "Flight time (s)")]
        public string FlightTime { get; set; }
    }
}

FlightWeb/Controllers/ConsumptionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using FlightWeb.DAL;
using FlightWeb.Models;

namespace FlightWeb.Controllers
{
    public class ConsumptionController : Controller
    {
        //private FlightDbContext db = new FlightDbContext();


       
        private ICustomRepository<Consumption> empRepository = null;
        private ICustomRepository<Flight> empRepository2 = null; 
        public ConsumptionController()
        {
            this.empRepository = new MyCustomRepository<Consumption>();
            this.empRepository2 = new MyCustomRepository<Flight>();
        }
        public ConsumptionController(ICustomRepository<Consumption> repository)
        {
            empRepository = repository;
        }

        // GET: Consumption
        public ActionResult Index(string thisFilter, string searchString, int? page)
        {
           
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = thisFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var Consumptions = empRepository.SelectDataById2(x => x.Flight);

             

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(Consumptions.ToPagedList(pageNumber, pageSize));
        }

        // GET: Consumption/Details/5
        public ActionResult Details(int? id)
        {

            if (id != null)
            {

                var consumption = empRepository.SelectDataById2(x => x.Flight).Where(ind => ind.ConsumptionId == id).FirstOrDefault(); 
                return View(consumption);
            }
            else
            {
                return RedirectToAction("Index");
            }

 
        }

        // GET: Consumption/Create/IdFLight
        public ActionResult Create(int? id)
        { 
            if(id != null)
            {
            var flight = empRepository2.SelectDataById(id);
            Consumption cons = new Consumption();
            cons.Flight = flight;
            return View(cons);
            }
            else
            {
                return RedirectToAction("Index");
            }
           
           
        }

        // POST: Consumption/Create
     
        [HttpPost] 
        public ActionResult Create( Consumption emp)
        {
            try
            {
                if (ModelState.IsValid)
            {
                    emp.FlightId = emp.Flight.FlightId;
                    emp.Flight = null;
                empRepository.InsertRecord(emp);
                empRepository.SaveRecord();
                return RedirectToAction("Index");
            }
        }
            catch (DataException e)
            {
                ModelState.AddModelError("", "Unable to save record.");
            }
            return View(emp);
        }

        // GET: Consumption/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var consumption = empRepository.SelectDataById2(x => x.Flight).Where(ind => ind.ConsumptionId == id).FirstOrDefault();
            consumption.FlightId = consumption.Flight.FlightId; 
            return View(consumption); 
        }

        // POST: Consumption/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Consumption emp)
        {
            try
            {


                if (ModelState.IsValid)
                {
                     emp.Flight = null;

                    empRepository.Update(emp);
                    empRepository.SaveRecord();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {

                ModelState.AddModelError("", "Unable to edit Consumption record.");
            }

            return View(emp);
        }

        // GET: Consumption/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(empRepository.SelectDataById(id)); 

        }

        // POST: Consumption/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    empRepository.DeleteRecord(id);
                    empRepository.SaveRecord();
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to delete the record.");
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
               // db.Dispose();
            }
            base.Dispose(disposing);
        }

        // POST: Consumption/Create

        [HttpPost]
        public decimal Calculate(Consumption emp, string FlightDistance, string FlightTime, int MethodCalcul)
        {
            if (MethodCalcul == 1)
            {
                return Math.Round((Convert.ToDecimal(FlightTime) * Convert.ToDecimal(emp.ConsumPerTime)) + emp.TakeoffEffort);
            }
            else if(emp.ConsumPerDistance.HasValue)
            { 
                return Math.Round(Convert.ToDecimal(FlightDistance) * Convert.ToDecimal(emp.ConsumPerDistance) + emp.TakeoffEffort); 
            }
            return 0;
        }
    }
}

FlightWeb/Controllers/FlightController.cs
using FlightWeb.DAL;
using FlightWeb.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.IO;
using System.Text;
using FlightWeb.Reports;
using AutoMapper;
using System.Web.UI.WebControls;
using System.Web.UI;

namespace FlightWeb.Controllers
{
    public class FlightController : Controller
    {

         

        private ICustomRepository<Flight> empRepository = null;
        private ICustomRepository<Consumption> empRepository2 = null;

        public FlightController()
        {
            this.empRepository = new MyCustomRepository<Flight>();
            this.empRepository2 = new MyCustomRepository<Consumption>();
        }
        public FlightController(ICustomRepository<Flight> repository)
        {
            empRepository = repository;
        }

        // GET: Flight
        public ActionResult Index(string thisFilter, string searchString, int? page)
        {
 

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = thisFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var Flights = from emp in empRepository.GetAllData()
                            select emp;
            if (!String.IsNullOrEmpty(searchString))
            {
                Flights = Flights.Where(emp => emp.FlightName.ToUpper().Contains(searchString.ToUpper()));
            }

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(Flights.ToPagedList(pageNumber, pageSize));

           // return View(Flights);
        }

       
        public ActionResult Create()
        {
            return View(new Models.Flight());
        }

        [HttpPost]
        public ActionResult Create(Flight emp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    empRepository.InsertRecord(emp);
                    empRepository.SaveRecord();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save record.");
            }
            return View(emp);
        }

        public ActionResult Edit(int? id)
        {
            var flight = empRepository.SelectDataById(id);
            if (flight != null )
            { 
              ViewBag.DestinationCode = flight.DestinationCode;
              ViewBag.DepartureCode = flight.DepartureCode;
              ViewBag.DepartureCode = flight.DepartureCode;
            }
            else
            {
                return RedirectToAction("Index");
            }
         
            return View(flight);
        }

        [HttpPost]
        public ActionResult Edit(Flight emp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    empRepository.Update(emp);
                    empRepository.SaveRecord();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {

                ModelState.AddModelError("", "Unable to edit Flight record.");
            }

            return View(emp);
        }

        public ActionResult Details(int? id)
        {

            if (id != null)
            {
                return View(empRepository.SelectDataById(id)); 
            }
            else
            { 
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(int? id)
        {
            return View(empRepository.SelectDataById(id));
        }

        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteFlight(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    empRepository.DeleteRecord(id);
                    empRepository.SaveRecord();
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to delete the record.");
            }
            return RedirectToAction("Index");

        }

        public ActionResult LoadReport()
        {
               var Consumptions = from emp2 in empRepository2.GetAllData()
                          select emp2;
            SummaryReport rpt = new SummaryReport();
            List<SummaryRep> model = new List<SummaryRep>();
            model  = (List<SummaryRep>)AutoMapper.Mapper.Map(Consumptions,model , typeof(IEnumerable<Consumption>), typeof(List<SummaryRep>) );
            rpt.Load();
            rpt.SetDataSource(model);
            DataSet ds = new DataSet();
             
            Stream s = rpt.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);

            return File(s, "application/pdf");


        }

        public ActionResult LoadReport2()
        {
            var Consumptions = from emp2 in empRepository2.GetAllData()
                               select emp2;
            SummaryReport rpt = new SummaryReport();
            List<SummaryRep> model = new List<SummaryRep>();
            model = (List<SummaryRep>)AutoMapper.Mapper.Map(Consumptions, model, typeof(IEnumerable<Consumption>), typeof(List<SummaryRep>));

            var gv = new GridView();
            gv.DataSource = model;
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=DemoExcel.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();

            return RedirectToAction("Index");

        }
    }
}

FlightWeb/Views/Flight/Create.cshtml
@model FlightWeb.Models.Flight
@{
    ViewBag.Title = "New Flight";
}

<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
<div class="repository-app panel panel-primary">
    <div class="panel-heading panel-head"><strong>New Flight</strong></div>
    <div class="panel-body">

        @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken();
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.FlightName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.FlightName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FlightName, "", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.FlightDistance, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.FlightDistance, new { htmlAttributes = new { @class = "form-control" } })
                </div>
               
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.DepartureCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.DepartureCode, new SelectList(Enumerable.Empty<SelectListItem>()), new { @onchange = "loadMaps()", @class = "form-control" })
                    @Html.HiddenFor(model => model.Departure)
                </div>
                @Html.LabelFor(model => model.FlightTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.FlightTime,  new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DestinationCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.DestinationCode, new SelectList(Enumerable.Empty<SelectListItem>()), new { @onchange = "loadMaps()", @class = "form-control" })
                    @Html.HiddenFor(model => model.Destination)
                </div>

            </div> 



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                    @Html.ActionLink("Return to List", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
             
                <div class="col-md-6" id="directions_panel" style="background-color:#E0FFFF;"></div>
             
        </div>

            }

        </div>
</div>
<div class="repository-app panel panel-primary">
    <div class="panel-heading panel-head"><strong>Google Maps</strong></div>
    <div class="panel-body">
        <div class="form-horizontal">
            <div id="map_canvas" style="height:400px;"></div>
        </div>
    </div>
</div>
<script>
  
    var code;
    var name; 
    var AirportList = JSON.parse(sessionStorage.getItem("AirportsFR"));  
    for (var i = 0; i < AirportList.length; i++) { 
        code = AirportList[i]["iata"];
        name = AirportList[i]["name"];

        if (name != "null") {
            $("#DepartureCode").append($("<option></option>").val(code).html(name));
            $("#DestinationCode").append($("<option></option>").val(code).html(name));
        }

    }
   
    function loadMaps() { 

        $("#Departure").val($("#DepartureCode option:selected").text());
        $("#Destination").val($("#DestinationCode option:selected").text());

        initialize($("#DepartureCode option:selected").text(), $("#DestinationCode option:selected").text()); 
    }

    
</script>

FlightWeb/Views/Flight/Delete.cshtml
@model FlightWeb.Models.Flight

@{
    ViewBag.Title = "Delete";
}

<div class="repository-app panel panel-primary">
    <div class="panel-heading panel-head"><strong> Delete Flight</strong></div>
    <div class="panel-body">

        <h3>Are you sure you want to delete this Flight?</h3>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.FlightName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FlightName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Departure)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Departure)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Destination)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Destination)
                </dd>

               

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color col-sm-offset-1 col-sm-10">
                    <input type="submit" value="Delete" class="btn btn-danger" /> &nbsp;
                    @Html.ActionLink("Back to List", "Index", "", htmlAttributes: new { @class = "btn btn-success" })
                </div>
            }
        </div>
    </div>
</div>

FlightWeb/Views/Flight/Details.cshtml
@model FlightWeb.Models.Flight

@{
    ViewBag.Title = "Details";
}


<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>

<div class="repository-app panel panel-primary">
    <div class="panel-heading panel-head">Flight Details of <strong> @Html.DisplayFor(model => model.FlightName)</strong></div>
    <div class="panel-body">

        <div>

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.FlightName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FlightName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Departure)
                </dt>

                <dd>
                    <div id="Departure">
                        @Html.DisplayFor(model => model.Departure)
                    </div>
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Destination)
                </dt>

                <dd>
                    <div id="Destination">
                        @Html.DisplayFor(model => model.Destination)
                    </div>
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.FlightDistance)
                </dt>

                <dd>
                    <div id="Destination">
                        @Html.DisplayFor(model => model.FlightDistance)
                    </div>
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.FlightTime)
                </dt>

                <dd>
                    <div id="Destination">
                        @Html.DisplayFor(model => model.FlightTime)
                    </div>
                </dd>


            </dl>
        </div>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Edit", "Edit", new { id = Model.FlightId }, new { @class = "btn btn-primary" }) &nbsp;
                @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-success" })
            </div>
        </div>

        <hr />
        <div class="form-group">
            <div class="col-md-6" id="directions_panel" style="background-color:#E0FFFF;"></div>
        </div>
    </div>
      
    </div>


<div class="repository-app panel panel-primary">
    <div class="panel-heading panel-head"><strong>Google Maps</strong></div>
    <div class="panel-body">
        <div class="form-horizontal">
            <div id="map_canvas" style="height:400px;"></div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {
        initialize($("#Departure").text(), $("#Destination").text());
    });
     
</script>

FlightWeb/Views/Flight/Edit.cshtml
@model FlightWeb.Models.Flight

@{
    ViewBag.Title = "Edit";
}

<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>

<div class="repository-app panel panel-primary">
    <div class="panel-heading panel-head">Edit Flight Details  of <strong> @Html.DisplayFor(model => model.FlightName)</strong></div>
    <div class="panel-body">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal panel-body">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.FlightId)

            <div class="form-group">
                @Html.LabelFor(model => model.FlightName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FlightName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FlightName, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.DepartureCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.DepartureCode, new SelectList(Enumerable.Empty<SelectListItem>()), new { @onchange = "loadMaps()", @class = "form-control" })
                    @Html.HiddenFor(model => model.Departure)
                </div>
                @Html.LabelFor(model => model.FlightDistance, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.FlightDistance, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DestinationCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.DestinationCode, new SelectList(Enumerable.Empty<SelectListItem>()), new { @onchange = "loadMaps()", @class = "form-control" })
                    @Html.HiddenFor(model => model.Destination)
                </div>
                @Html.LabelFor(model => model.FlightTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.FlightTime, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                    @Html.ActionLink("Return to List", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
             
                <div class="col-md-6" id="directions_panel" style="background-color:#E0FFFF;"></div>
           
        </div>
        }

    </div>
</div> 
<div class="repository-app panel panel-primary">
    <div class="panel-heading panel-head"><strong>Google Maps</strong></div>
    <div class="panel-body">
        <div class="form-horizontal">
            <div id="map_canvas" style="height:400px;"></div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {
        loadMaps();
    });

    var AirportList = JSON.parse(sessionStorage.getItem("AirportsFR"));

    var depCode = @Html.Raw(Json.Encode(ViewBag.DepartureCode));
    var destCode = @Html.Raw(Json.Encode(ViewBag.DestinationCode));  
    var code;
    var name;

    for (var i = 0; i < AirportList.length; i++) {

        code = AirportList[i]["iata"];
        name = AirportList[i]["name"];
        if (name != "null") {

            if (code == depCode) {
                $("#DepartureCode").append($("<option Selected></option>").val(code).html(name));
            } else {
                $("#DepartureCode").append($("<option></option>").val(code).html(name));
            }
            if (code == destCode) {
                $("#DestinationCode").append($("<option Selected></option>").val(code).html(name));
            } else {
                $("#DestinationCode").append($("<option></option>").val(code).html(name));
            }
          
        }

    }

    function loadMaps() {

        $("#Departure").val($("#DepartureCode option:selected").text());
        $("#Destination").val($("#DestinationCode option:selected").text()); 
        initialize($("#DepartureCode option:selected").text(), $("#DestinationCode option:selected").text());
    }

     
</script>

FlightWeb/Views/Flight/Index.cshtml
@model IEnumerable<FlightWeb.Models.Flight>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>

@{
    ViewBag.Title = "Flight List";
    var pagedlist = (PagedList.IPagedList)Model;
}


<div class="repository-app panel panel-primary">
    <div class="panel-heading"><strong> Flight List</strong></div>
    <div class="panel-body">
        <p>
            @Html.ActionLink("Add New Flight", "Create", "", htmlAttributes: new { @class = "btn btn-success" })
            <input type="button" value="Summary Report" class="btn btn-primary" style="color:white;" onclick="location.href='@Url.Action("LoadReport", "Flight")'" />
            <input type="button" value="Report (Excel)" class="btn btn-primary" style="color:white;" onclick="location.href='@Url.Action("LoadReport2", "Flight")'" />

        </p>

        @using (Html.BeginForm("Index", "Flight", FormMethod.Post))
    {
        <p>
            Flight Name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
} 
        <table class="table table-striped">
            <tr>
                <th>@Html.DisplayNameFor(model => model.FlightName)</th>
                <th>@Html.DisplayNameFor(model => model.Departure)</th>
                <th>@Html.DisplayNameFor(model => model.Destination)</th>
                <th></th>

            </tr>

            @foreach (var item in Model)
        {


            <tr>
                <td>@Html.DisplayFor(mitem => item.FlightName)</td>
                <td>@Html.DisplayFor(mitem => item.Departure)</td>
                <td>@Html.DisplayFor(mitem => item.Destination)</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.FlightId }, new { @class = "btn btn-primary", @style = "color:white" })
                    @Html.ActionLink("Details", "Details", new { id = item.FlightId }, new { @class = "btn btn-success", @style = "color:white" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.FlightId }, new { @class = "btn btn-danger", @style = "color:white" })
                    @Html.ActionLink("Fuel Consumption", "Create", "Consumption", new { id = item.FlightId }, new { @class = "btn btn-warning", @style = "color:white" })
            </tr>
    }

        </table>
    </div>


    <div class="panel-footer">
        Page @(pagedlist.PageCount < pagedlist.PageNumber ? 0 : pagedlist.PageNumber) of @pagedlist.PageCount

        @Html.PagedListPager(pagedlist, page => Url.Action("Index",
                new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

    </div>


</div>

<script>
    var AirportsList;
    function readTextFile(file, callback) {
        var rawFile = new XMLHttpRequest();
        rawFile.overrideMimeType("application/json");
        rawFile.open("GET", file, true);
        rawFile.onreadystatechange = function () {
            if (rawFile.readyState === 4 && rawFile.status == "200") {
                callback(rawFile.responseText);
            }
        }
        rawFile.send(null);
    }

    //usage:
    readTextFile("/airportsFR.json", function (text) {
        if (sessionStorage.getItem("AirportsFR") === null) {
        //    var data = JSON.parse(text);
        //    console.log(data);
            sessionStorage.setItem("AirportsFR", text);
        }
    });

    function getAiroportName(code){

         AirportsList = sessionStorage.getItem("AirportsFR");
        if (AirportsList === null) {
            for (var i = 0; i < AirportsList.length; i++) {
                if (code = AirportList[i]["iata"]) return AirportList[i]["name"];
            }
        }
    };

            </script>